[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --no-frozen-lockfile || npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NIXPACKS_NODE_VERSION = "20"
NODE_VERSION = "20"
