import React, { useState } from 'react';
import {
  Landmark,
  FileCheck2,
  DollarSign,
  Calculator,
  ShieldCheck,
  Clock,
  CheckCircle2,
  Download,
  AlertCircle,
  ExternalLink,
} from 'lucide-react';
import { safeDownload } from '../../utils/safeDownload';

export const AdminRegistration: React.FC<{ navigate: (path: string) => void }> = () => {
  const [propertyValue, setPropertyValue] = useState<number>(4500000);
  const [propertyAge, setPropertyAge] = useState<'old' | 'new'>('old'); // Ancient vs Neuf (reduced fees)
  const [registrationRegion, setRegistrationRegion] = useState('Alpes-Maritimes');

  // French Notarial Tax Calculation Formula
  const calculateFees = () => {
    const val = Number(propertyValue) || 0;
    const transferTaxRate = propertyAge === 'old' ? 0.05806 : 0.00715; // Droits de mutation / TPF
    const transferTax = val * transferTaxRate;
    const notaryEmoluments = val * 0.00814; // Scale emoluments
    const securityContribution = val * 0.001; // Contribution de sécurité immobilière
    const total = transferTax + notaryEmoluments + securityContribution;

    return {
      transferTax: Math.round(transferTax),
      notaryEmoluments: Math.round(notaryEmoluments),
      securityContribution: Math.round(securityContribution),
      total: Math.round(total),
    };
  };

  const fees = calculateFees();

  const handleExportCalculation = () => {
    const reportText = `
OFFICIAL LAND REGISTRATION & TAX CALCULATION - KRETZ LEGAL
Property Value: €${propertyValue.toLocaleString()} EUR
Property Category: ${propertyAge === 'old' ? 'Ancien (Standard Transfer Tax)' : 'Neuf (Reduced Transfer Tax)'}
Department: ${registrationRegion}

NOTARIAL TAX & STAMP DUTY BREAKDOWN:
1. Droits de Mutation / Taxe de Publicité Foncière: €${fees.transferTax.toLocaleString()}
2. Émoluments du Notaire (Tarif Réglementé): €${fees.notaryEmoluments.toLocaleString()}
3. Contribution de Sécurité Immobilière (CSI 0.10%): €${fees.securityContribution.toLocaleString()}

TOTAL REGISTRATION & FILING TAXES: €${fees.total.toLocaleString()}
Generated by Kretz Legal Notarial Fee Calculator
    `;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    safeDownload(blob, `Land_Registration_Fee_Report_${propertyValue}.txt`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-mono font-semibold bg-blue-50 text-blue-800 border border-blue-200 mb-2">
            <Landmark className="w-3.5 h-3.5" />
            <span>LAND REGISTRATION & DEED FILING</span>
          </div>
          <h1 className="font-serif text-2xl font-bold text-slate-900">
            Land Registry Filing & Tax Stamp Management
          </h1>
          <p className="text-xs text-slate-500">
            Filing deeds with the Land Registry (Service de la Publicité Foncière), tax stamp calculation, and property tax breakdown.
          </p>
        </div>

        <button
          onClick={handleExportCalculation}
          className="px-4 py-2 bg-slate-950 hover:bg-slate-900 text-white font-semibold text-xs rounded-xl shadow-md transition flex items-center gap-2"
        >
          <Download className="w-4 h-4 text-amber-400" />
          <span>Export Registration Tax Statement</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Interactive Calculator */}
        <div className="lg:col-span-6 bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-5">
          <h2 className="font-bold text-sm text-slate-900 flex items-center gap-2">
            <Calculator className="w-4 h-4 text-blue-600" />
            <span>Notarial Transfer Tax & Stamp Fee Calculator</span>
          </h2>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1.5">
              Property Agreed Purchase Price (EUR)
            </label>
            <div className="relative">
              <input
                type="number"
                value={propertyValue}
                onChange={(e) => setPropertyValue(Number(e.target.value))}
                className="w-full text-xs pl-8 pr-3 py-3 bg-slate-50 border border-slate-300 rounded-xl focus:bg-white focus:ring-2 focus:ring-slate-900 font-mono text-sm font-bold"
              />
              <span className="absolute left-3 top-3 text-slate-400 font-mono font-bold">€</span>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                Property Age / Category
              </label>
              <select
                value={propertyAge}
                onChange={(e) => setPropertyAge(e.target.value as any)}
                className="w-full text-xs p-2.5 bg-slate-50 border border-slate-300 rounded-xl font-medium"
              >
                <option value="old">Ancien (Standard ~7.5% - 8%)</option>
                <option value="new">Neuf (VEFA / Reduced ~2% - 3%)</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                Department Jurisdiction
              </label>
              <select
                value={registrationRegion}
                onChange={(e) => setRegistrationRegion(e.target.value)}
                className="w-full text-xs p-2.5 bg-slate-50 border border-slate-300 rounded-xl font-medium"
              >
                <option value="Alpes-Maritimes">06 - Alpes-Maritimes (Cannes / Nice)</option>
                <option value="Paris">75 - Paris</option>
                <option value="Var">83 - Var (Saint-Tropez)</option>
                <option value="Bouches-du-Rhône">13 - Bouches-du-Rhône (Aix)</option>
              </select>
            </div>
          </div>

          {/* Fee Calculation Breakdown Result Card */}
          <div className="p-5 bg-slate-900 text-white rounded-2xl space-y-4 font-mono text-xs">
            <div className="flex items-center justify-between text-amber-400 font-bold border-b border-slate-800 pb-2">
              <span>ESTIMATED REGISTRATION FEES</span>
              <span className="text-base font-bold text-white">€{fees.total.toLocaleString()}</span>
            </div>

            <div className="space-y-2 text-slate-300">
              <div className="flex justify-between">
                <span>Droits de Mutation / Taxe TPF:</span>
                <span className="font-bold text-white">€{fees.transferTax.toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span>Notary Regulated Emoluments:</span>
                <span className="font-bold text-white">€{fees.notaryEmoluments.toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span>Contribution Sécurité Immobilière (0.10%):</span>
                <span className="font-bold text-white">€{fees.securityContribution.toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Pending Filing Filings Status Table */}
        <div className="lg:col-span-6 bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-4">
          <h2 className="font-bold text-sm text-slate-900">
            Pending Land Registry Filings (Télé@ctes Queue)
          </h2>

          <div className="space-y-3">
            <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
              <div className="flex items-center justify-between text-xs font-mono">
                <span className="font-bold text-slate-900">FILING-2026-CAN-08</span>
                <span className="bg-emerald-100 text-emerald-800 font-bold px-2 py-0.5 rounded text-[10px]">
                  REGISTERED & STAMPED
                </span>
              </div>
              <p className="text-xs text-slate-600 font-medium">
                Villa Ramingao — Cadastre AH-102 (Cannes)
              </p>
              <div className="text-[10px] text-slate-400 font-mono flex items-center justify-between pt-1 border-t border-slate-200">
                <span>Droits acq: €351,200</span>
                <span>Télé@ctes Ref: T-9948102</span>
              </div>
            </div>

            <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
              <div className="flex items-center justify-between text-xs font-mono">
                <span className="font-bold text-slate-900">FILING-2026-PAR-14</span>
                <span className="bg-amber-100 text-amber-800 font-bold px-2 py-0.5 rounded text-[10px]">
                  IN TRANSMISSION
                </span>
              </div>
              <p className="text-xs text-slate-600 font-medium">
                Hôtel Particulier Triangle d'Or — Paris 8e
              </p>
              <div className="text-[10px] text-slate-400 font-mono flex items-center justify-between pt-1 border-t border-slate-200">
                <span>Droits acq: €1,240,000</span>
                <span>Télé@ctes Ref: Pending Ack</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
